### ISSUE TITLE
Automatically run bin/buildout after running bin/develop

### ISSUE THREAD

**Issue by zupo** [fschulze/mr.developer#181]
I don't use bin/develop very frequently, but I do use regularly. And every time a few weeks go by without using it I always forget to run bin/buildout after I run bin/develop.

Would be lovely if there was a setting (off by default) that would tell mr.developer "hey please run this command after you finish" and I can tell it to run bin/buildout for me.

**Comment by mauritsvanrees** [comment]
👎  This would be yet another option. And it can lead to people asking for various related options. For example: for which commands should this be done? Obviously for activate and checkout, obviously not for status. But how about the update command? Some will want to run bin/buildout after this (the `setup.py` of a package may have a new dependency), some not. And it would then be nice if mr.developer could detect if any packages had actual changes, otherwise there would be no need for a buildout, but that means extra complexity in the code.

There needs to be a balance in the value of a feature request and the added complexity for the developers and the users. For me, the balance in this feature request is off. But we can see if more people want this.

**Comment by fschulze** [comment]
I'm also 👎 on this. I often activate and deactivate several packages before running buildout. And @mauritsvanrees has some other good points.

You are also told by mr.developer not to forget to run buildout 😄
